### PR TITLE
feat(HTTP): Missing APIs for Account and Validator By Number

### LINKED ISSUE #528: HTTP: Add Missing APIs for Account and Validator By Number
## Describe the problem you'd like to have solved

The HTTP module in Pactus works like a simple HTTP server to provide some information about the node. 
You can think of it as a very basic block explorer.

Currently, there are two APIs missing in the HTTP module: `GetAccountByNumber` and `GetValidatorByNumber`.

### Describe the ideal solution

The first thing you need to do is to add these routes:

```
/account/number/{number}
/validator/number/{number}
```
Then add the `GetAccountByNumberHandler` handlers inside [account.go](https://github.com/pactus-project/pactus/blob/main/www/http/account.go) and  `GetValidatorByNumberHandler` inside [validator.go](https://github.com/pactus-project/pactus/blob/main/www/http/validator.go).

Please don't forget to write tests for both APIs.

### PR DESCRIPTION
**Pull request by kehiy**
## Description
I just add the two handler and route for get Validator and Account by number.
I wrote test for both!

## Related issue(s)
fixed #528

### CODE REVIEW

**Comment by kehiy** [comment]
I donsn't make any change on this part:
--- FAIL: TestIterateAccounts (0.16s)
    account_test.go:184: 
        	Error Trace:	/home/runner/work/pactus/pactus/store/account_test.go:184
        	Error:      	Should be true
        	Test:       	TestIterateAccounts
        	
why there is error here?

**Comment by kehiy** [comment]
@b00f 
I'm trying to fix godec G109 issue but there is no way for it!
the number should be an int32
is there any way to fix it?

**Comment by b00f** [comment]
@kehiy so many commits, please rebase your branch

@Ja7ad Could you please review the changes?

**Comment by Ja7ad** [comment]
> @kehiy so many commits, please rebase your branch
> 
> @Ja7ad Could you please review the changes?

Sry, If impossible you review it, I'm not available until Saturday next week.

**Comment by b00f** [comment]
Sure @Ja7ad Take care

**Comment by kehiy** [comment]
> @kehiy so many commits, please rebase your branch
> 
> @Ja7ad Could you please review the changes?

should I rebase all the commits in one?

**Pull request closed without merging**
