### PR TITLE
Extend GRPC to include missing CAPNP functionality

### PR DESCRIPTION
**Pull request by braewoods**
## Description

This extends the GRPC module to include missing CAPNP module functionality. This is important for a proper conversion from CAPNP module to GRPC module to be possible within the current HTTP module.

## Related issue(s)

This advances #418 but it does not fulfill it yet.

## Checklist

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] CHANGELOG is updated.

### CODE REVIEW

**Comment by braewoods** [comment]
Force pushed a small change to make the linter happy.

**Comment by b00f** [comment]
@braewoods Thanks. The PR looks good to me, however the `PeerInfo` in gRPC is a little bit confusing. This is not related to this PR. So I will create another issue and try to discuss about ti.

**Review by b00f — APPROVED** [review]

**Comment by braewoods** [comment]
I don't know what there is to discuss though. I personally just found it weird that it was using virtually the same information as the network information so I made it into a reusable type to reduce duplication.

**Comment by b00f** [comment]
I created #425 for more discussion

**Pull request merged**
