### PR TITLE
chore: add Node Dragon bootstrap node

### PR DESCRIPTION
**Pull request by quangtuyen88**
## Description

adding Node Dragon Bootstrap Node

### CODE REVIEW

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
@quangtuyen88 Thanks

**Review by b00f — APPROVED** [review]

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
@quangtuyen88 
Kindly resolve the conflicts or submit a new pull request (PR). 
Apologies for any inconvenience caused.

**Comment by quangtuyen88** [comment]
Hello @b00f . pls help merge. Thanks

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
@quangtuyen88 Thanks

**Comment by quangtuyen88** [comment]
solved @b00f

**Comment by b00f** [comment]
@quangtuyen88 
Please enable relay and auto NAT services. Read here for more information:
https://github.com/pactus-project/pactus/blob/main/docs/bootstrap.md#bootstrap-node-configuration

**Comment by quangtuyen88** [comment]
Hello @b00f ..i think that's issue with my firewall.. pls very again if it's oke now

**Review by themantre — APPROVED** [review]

**Comment by themantre** [comment]
@quangtuyen88 It still has conflicts. Close this PR and open a new one please

**Pull request closed without merging**
