### PR TITLE
BLS12381 pure go

### PR DESCRIPTION
**Pull request by b00f**
## Description

In this PR the [herumi/bls](https://github.com/herumi/bls) library is replaced with [kilic/bls12-381](https://github.com/kilic/bls12-381). Since Herumi is written in C, it had compiling issues from time to time.
Also, we don't have any packages with CGO, we can build the software for different [platforms](https://go.dev/doc/install/source#environment), which is a big advantage. From now on, we should not allow installing any library with CGO packages.

## Related issue(s)

Fixing #380 and #381 

## Checklist

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] CHANGELOG is updated.

### CODE REVIEW

**Comment by b00f** [comment]
@jwmdev No more cgo anymoe for daemon and wallet.
Hopefully we can have GUI that can build for ARM architecture.

**Review by jwmdev — COMMENTED** [review]
I have re-run the data race detection with logs enabled, it giving warning, you can follow the logs and verify that everything is OK before we approve this PR.

**Comment by b00f** [comment]
@jwmdev Thanks. I will test it soon. Still it is not finalized yet. Thanks for reporting it.

**Comment by b00f** [comment]
@jwmdev Data race issue is fixed.

**Review by jwmdev — APPROVED** [review]

**Pull request merged**
