### PR TITLE
chore: add bootstrap address for p10node

### PR DESCRIPTION
**Pull request by pierreneter**
## Description

add `p10node` to bootstrap node

### CODE REVIEW

**Comment by b00f** [comment]
@pierreneter 
Please address the JSON format issue. You can verify the correctness of the data using https://jsonlint.com/.

**Comment by pierreneter** [comment]
thank you @b00f, I fixied it

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
@pierreneter 
Please resolve the conflicts...

**Comment by pierreneter** [comment]
done 🙌, @b00f

**Review by themantre — APPROVED** [review]

**Pull request merged**
