### PR TITLE
feat(grpc): update swagger API to version 1.1

### PR DESCRIPTION
**Pull request by b00f**
## Description

This PR updates the Swagger APIs to version 1.1. In this new version we follow this convention:

- Each API starts with `pactus`
- Each API should follow the same path as gRPC APIs
- Comments should be on top of the field to generate commented codes.

### CODE REVIEW

**Review by kehiy — APPROVED** [review]
Looks good. I just have one question. What's the purpose of the `pactus` prefix instead of `v1`, and why we removed the `v1` prefix? Isn't that helpful when we add the next versions over time?

**Comment by b00f** [comment]
>  Isn't that helpful when we add the next versions over time?
I saw that swagger also has version, we bump it to v1.1 in this PR

**Comment by kehiy** [comment]
what about SDKs and users that use these endpoints on code? they don't work with Swagger in code and they don't have access to the Swagger version.

**Comment by b00f** [comment]
Even we add version to API, they still need to update their code. So this version is not really helpful for them

**Review by amirvalhalla — APPROVED** [review]

**Pull request merged**
