### PR TITLE
chore(config): update bootstrap nodes for Testnet

### PR DESCRIPTION
**Pull request by themantre**
## Description

This PR adds new node as bootstrap node for the Testnet. The rest of the nodes should be updated.

### CODE REVIEW

**Review by Ja7ad — APPROVED** [review]

**Review by alidevjimmy — APPROVED** [review]

**Comment by b00f** [comment]
We can add: `/ip4/65.108.211.187/tcp/21777/p2p/12D3KooWB42BLfzxSF5SMhSTSEyfJ6yhSM8togLfExrRWFMJeb5u` (@Mr-HoDL58  Node)

**Comment by b00f** [comment]
More nodes....
```
/ip4/103.27.206.208/tcp/21777/p2p/12D3KooWMTDwDTBMaf2Sem5tWRe1dB6PFY8LeqkZ2e5drrbbPTDn // andrut.pactus.testnet
/ip4/65.108.142.81/tcp/21777/p2p/12D3KooWAdRga2NCbaPfVgSEzAAZW2psfJmPi3PFJzF81qbccJsR // CherryValidator
/ip4/95.217.89.202/tcp/21777/p2p/12D3KooWH3S9gMYybr1pd4K5o3CBLbZLQ1REKBsPWt6NWPi4bgPn // CodeBlockLab
/ip4/65.109.234.125/tcp/21777/p2p/12D3KooWPWE8QwZxd32ui9DL115vmdcFo3cudGfVgHTX9Bo4HFEB // Sensifai
```

**Comment by b00f** [comment]
@Ja7ad you node info is correct? The port is correct?

**Comment by Ja7ad** [comment]
> @Ja7ad your node info is correct? The port is correct?

Port close, I fixed it. Currently is open.

**Pull request merged**
