### PR TITLE
chore: removing reachability status from hello message

### PR DESCRIPTION
**Pull request by nagarajmanjunath**
## Description

* Removed ReachabilityStatus.

## Related issue(s)

- removed ReachabilityStatus from hello in new message and sync.

### CODE REVIEW

**Review by kehiy — CHANGES_REQUESTED** [review]
In handler_hello_test.go file line 102.

remove this:
`assert.Equal(t, p.Agent, version.Agent()+"/reachability=public")`

change it to:
`assert.Equal(t, p.Agent, version.Agent())`

It should fix pipeline issues.

**Comment by b00f** [comment]
Here also missed: https://github.com/pactus-project/pactus/blob/80e1935e8d9185ed41199769f08376a804431790/www/grpc/network.go#L45

Please confirm @kehiy ?

**Comment by kehiy** [comment]
@b00f correct, this should be removed also.

**Comment by themantre** [comment]
@nagarajmanjunath please use your own fork, and don't create working branch on Pactus repo

**Pull request closed without merging**
