### PR TITLE
feat: enable bandwidth router metric

### PR DESCRIPTION
**Pull request by amirvalhalla**
## Description
enable bandwidth router metric to monitoring network layer better.

### CODE REVIEW

**Comment by b00f** [comment]
Make sure it is only enables when metrics are enabled.

**Comment by amirvalhalla** [comment]
> Make sure it is only enables when metrics are

**Comment by b00f** [comment]
Also use this format for the imports: `lp2pmetrics "github.com/libp2p/go-libp2p/core/metrics"`

**Comment by amirvalhalla** [comment]
> Also use this format for the imports: `lp2pmetrics "github.com/libp2p/go-libp2p/core/metrics"`

@b00f 
fixed.

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
LGTM. Thanks @amirvalhalla

**Pull request merged**
