### PR TITLE
chore: update Swagger-UI to latest version

### PR DESCRIPTION
**Pull request by Ja7ad**
## Description

Updating Swagger-UI to the latest [version](https://github.com/swagger-api/swagger-ui/releases)

### CODE REVIEW

**Review by b00f — COMMENTED** [review]
Please make sure the latest LICENSE is attached here.
Also, double check the README. (Keep it)

**Comment by Ja7ad** [comment]
> Please make sure the latest LICENSE is attached here.
> Also, double check the README. (Keep it)

All things is latest

**Comment by b00f** [comment]
Please put LICENSE back and README as well.

**Comment by Ja7ad** [comment]
> Please put LICENSE back and README as well.

done

**Review by b00f — APPROVED** [review]

**Pull request merged**
