### PR TITLE
chore: add bootstrap address for diszell2008

### PR DESCRIPTION
**Pull request by diszell2008**
## Description

Adding bootstrap address for diszell2008

### CODE REVIEW

**Comment by b00f** [comment]
@diszell2008 
The address is invalid. Please provide the correct address

**Comment by b00f** [comment]
@diszell2008 

Please enable relay and auto nat services.
Please refer to this document for more help on running Bootstrap node: https://github.com/pactus-project/pactus/blob/main/docs/bootstrap.md

**Comment by diszell2008** [comment]
Enabled sir!

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
@diszell2008 
Merged with thanks

**Pull request merged**
