### PR TITLE
feat: implementing pip-9

### PR DESCRIPTION
**Pull request by amirvalhalla**
## Description

This PR implemented [pip-9](https://pips.pactus.org/PIPs/pip-9).

### CODE REVIEW

**Comment by Ja7ad** [comment]
> ## Description
> 
> this PR implemented [pip-9](https://pips.pactus.org/PIPs/pip-9)
> 

Your proposal is Draft and not accepted by team, how to implement?

@b00f

**Comment by b00f** [comment]
@Ja7ad It is not merged yet. Waiting for the approval.

**Review by kehiy — COMMENTED** [review]
Everything looks good.
We can merge it after PIP-9 is accepted by the pactus lab.
Also, that's good to add something like: `removing the stamp from transaction` at the end of the PR title.

**Comment by amirvalhalla** [comment]
> Everything looks good. We can merge it after PIP-9 is accepted by the pactus lab. Also, that's good to add something like: `removing the stamp from transaction` at the end of the PR title.
> 
> @amirvalhalla Thanks

@kehiy 
I don't think so, we need to mention it at the end of PR title, because we referred it to `PIP-9`

**Comment by kehiy** [comment]
> I don't think so, we need to mention it at the end of PR title, because we referred it to `PIP-9`

That makes sense too, it's up to you.

**Review by b00f — APPROVED** [review]

**Pull request merged**
