### PR TITLE
feat: GarbageCollector

### LINKED ISSUE #546: Garbage collection for peerset
## Describe the problem you'd like to have solved

Once a node joins the network, it sends `hello` [message](https://github.com/pactus-project/pactus/blob/a75fe24372bd3cd35d6a6c0d725f26e84a1c0357/sync/bundle/message/hello.go#L20) and announce its peer ID and consensus keys. 
However, we currently don't have a mechanism to remove a node from the [peer list](https://github.com/pactus-project/pactus/blob/a75fe24372bd3cd35d6a6c0d725f26e84a1c0357/sync/peerset/peer_set.go#L19C23-L19C24) once it goes offline.

### Describe the ideal solution

We need to establish a mechanism for garbage collection. A garbage node should have a clear definition.
A node can be considered "garbage" if we haven't heard from it in the last few hours.
Each peer has a property named [last_seen](https://github.com/pactus-project/pactus/blob/a75fe24372bd3cd35d6a6c0d725f26e84a1c0357/sync/peerset/peer.go#L24) that gets updated each time we receive data from that node.
We can use this property to calculate how long a node has been offline. 
If a node has been offline for more than a day, we should remove it from the peer list. 
The garbage collector check could be scheduled to run daily

### Alternatives and current work-around

Currently, the only workaround is to restart the node.

### PR DESCRIPTION
**Pull request by kehiy**
## Description
I added the Garbage Collector function for removing the offline peers each 24 hours

## Related issue

- Fixes #546

### CODE REVIEW

**Comment by kehiy** [comment]
@b00f you can review it know
I understood the test completely

**Comment by b00f** [comment]
@kehiy update [RandomString](https://github.com/pactus-project/pactus/blob/f01370fe659c6f9e42cc2f116866562d22561501/util/testsuite/testsuite.go#L140) function and change 52 to 51, will fix the broken test. We have just recently introduced the TestSuite.

**Comment by b00f** [comment]
We need to make sure that Context will be set properly #368

**Comment by kehiy** [comment]
@b00f I changed it to 51 and first issue is fixed!
but there is another issue:
```
Error Trace:	/home/kehiy/code/pactus/sync/peerset/peer_set_test.go:296
            	Error:      	Should be zero, but was 2
            	Test:       	TestGarbageCollector/Removing_peers
```
I think the problem is from this lines:
```go
time.Sleep(1 * time.Second)
		cancel()
```

**Comment by kehiy** [comment]
> We need to make sure that Context will be set properly #368

Isn't it better to solve them all at once in a single pull request?

**Comment by b00f** [comment]
Give me the seed, then I can reproduce it here

**Comment by b00f** [comment]
> Isn't it better to solve them all at once in a single pull request?

Yes. Opening new PR for this small fixes is not a good option. 

Here, I think we can fix it by reducing `clearanceTimeout` to 500 millisecond

**Comment by kehiy** [comment]
> > Isn't it better to solve them all at once in a single pull request?
> 
> Yes. Opening new PR for this small fixes is not a good option.
> 
> Here, I think we can fix it by reducing `clearanceTimeout` to 300 millisecond

i fixed it

yes, maybe i go to work on this after resolving the address validator

**Comment by kehiy** [comment]
@b00f its still need approving

**Comment by b00f** [comment]
@kehiy please rebase your branch. It has some conflict with the codebase.

**Comment by kehiy** [comment]
> @kehiy please rebase your branch. It has some conflict with the codebase.

can I resolve conflicts here? in github??
I think its mush easier

**Pull request closed without merging**
